version: '2'
services:
  app:
    container_name: syspass-app
    image: nuxsmin/docker-syspass:3.0.4
    restart: always
    ports:
      - "80"
      - "443"
    links:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
  db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    environment:
      MARIADB_ROOT_PASSWORD: "$MARIADB_ROOT_PASSWORD"
      MARIADB_DATABASE: "$MARIADB_DATABASE"
      MARIADB_USER: "$MARIADB_USER"
      MARIADB_PASSWORD: "$MARIADB_PASSWORD"
    ports:
      - "3306"
    volumes:
      - syspass-db:/var/lib/mysql

volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}
